### ISSUE TITLE
cdn links for jsfiddle no longer work

### ISSUE THREAD

**Issue by copremesis** [Zenoo/CSS3-Cube#3]
**Describe the bug**
see title
**To Reproduce**
click on jsfiddle

**Expected behavior**
a working demo
**Screenshots**

<img width="677" alt="Screen Shot 2020-07-29 at 5 14 33 PM" src="https://user-images.githubusercontent.com/611899/88859279-08834200-d1bf-11ea-967d-9df56e4a6e03.png">

<img width="561" alt="Screen Shot 2020-07-29 at 5 13 09 PM" src="https://user-images.githubusercontent.com/611899/88859238-e984b000-d1be-11ea-82aa-1c9aec99eb20.png">

**Desktop (please complete the following information):**
n/a
**Smartphone (please complete the following information):**
 n/a
**Additional context**

I recommend codepen.io as they didn't remove vim keybindings like jsfiddle 😞 

here's a working demo https://codepen.io/copremesis/pen/NWxZdBZ

**Comment by Zenoo** [comment]
Thanks for the heads up @copremesis.
I fixed it by using `unpkg.com` instead.
